name = "glqr"
version = "1.0.0"

description = "Simple Gleam library for generating QR codes."
licences = ["Apache-2.0"]
repository = { type = "github", user = "imcquee", repo = "glqr" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.5.4 and < 2.0.0"
